//Global
export const PAGE_LOADED = "PAGE_LOADED";

//ARTICLE list
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';
export const RESET_ARTICLES = 'RESET_ARTICLES';

//Create new ARTICLE
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE';
export const RESET_NEW_ARTICLE = 'RESET_NEW_ARTICLE';

//Validate ARTICLE fields like Title, Categries on the server
export const VALIDATE_ARTICLE_FIELDS = 'VALIDATE_ARTICLE_FIELDS';
export const VALIDATE_ARTICLE_FIELDS_SUCCESS = 'VALIDATE_ARTICLE_FIELDS_SUCCESS';
export const VALIDATE_ARTICLE_FIELDS_FAILURE = 'VALIDATE_ARTICLE_FIELDS_FAILURE';
export const RESET_ARTICLE_FIELDS = 'RESET_ARTICLE_FIELDS';

//Fetch ARTICLE
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE';
export const RESET_ACTIVE_ARTICLE = 'RESET_ACTIVE_ARTICLE';

//Delete ARTICLE
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE';
export const RESET_DELETED_ARTICLE = 'RESET_DELETED_ARTICLE';
